services:
  zabbix-agent:
    image: zabbix/zabbix-agent:latest
    container_name: zabbix-agent
    environment:
      - ZBX_HOSTNAME=$ZBX_HOSTNAME
      - ZBX_SERVER_HOST=$ZBX_SERVER_HOST
      - ZBX_PASSIVESERVERS=$ZBX_PASSIVESERVERS
      - ZBX_ACTIVESERVERS=$ZBX_ACTIVESERVERS
    init: true
